#!/usr/bin/env bash
# Creates the server's .env for the Oracle demo: fresh random secrets,
# generated here and written straight to disk, never printed.
#
#   ops/init-env.sh streetboardman.duckdns.org
#
# Run it once, BEFORE the first `docker compose up`: Postgres sets the
# app role's password only when its volume is first created, so changing
# COMPOSE_APP_DB_PASSWORD afterwards needs a manual ALTER ROLE.
# Demo account logins go to ~/DEMO_ACCOUNTS.txt (outside the repo).
set -euo pipefail

DOMAIN="${1:?usage: ops/init-env.sh <domain>}"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_DIR/.env"
ACCOUNTS_FILE="$HOME/DEMO_ACCOUNTS.txt"

if [ -e "$ENV_FILE" ]; then
  echo "Refusing to overwrite $ENV_FILE (delete it yourself if you really mean to)." >&2
  exit 1
fi

secret() { openssl rand -hex 32; }
# Demo logins get typed by hand, so shorter — still 16 hex chars, which
# also clears the 12-character staff password rule for the admin.
login() { openssl rand -hex 8; }

umask 077
ADMIN_PW="$(login)"
BOARDMAN_PW="$(login)"
BETTER_PW="$(login)"

cat > "$ENV_FILE" <<EOF
# Generated by ops/init-env.sh on $(date -u +%Y-%m-%d). Never commit this file.
COMPOSE_PATH_SEPARATOR=:
COMPOSE_FILE=docker-compose.yml:docker-compose.oracle.yml
DEMO_DOMAIN=$DOMAIN

COMPOSE_DB_OWNER_PASSWORD=$(secret)
COMPOSE_APP_DB_PASSWORD=$(secret)
COMPOSE_JWT_ACCESS_SECRET=$(secret)
COMPOSE_JWT_REFRESH_SECRET=$(secret)
COMPOSE_JWT_MFA_SECRET=$(secret)

SEED_ADMIN_PHONE=08000000000
SEED_ADMIN_PASSWORD=$ADMIN_PW
SEED_BOARDMAN_PHONE=08011111111
SEED_BOARDMAN_PASSWORD=$BOARDMAN_PW
SEED_BETTER_PHONE=08022222222
SEED_BETTER_PASSWORD=$BETTER_PW
EOF
chmod 600 "$ENV_FILE"

cat > "$ACCOUNTS_FILE" <<EOF
StreetBoardman demo accounts — https://$DOMAIN
(created $(date -u +%Y-%m-%d); exist only after the seed has run)

Admin     phone 08000000000   password $ADMIN_PW   (MFA setup required at first login)
Boardman  phone 08011111111   password $BOARDMAN_PW
Better    phone 08022222222   password $BETTER_PW
EOF
chmod 600 "$ACCOUNTS_FILE"

echo "Wrote $ENV_FILE (chmod 600) with:"
grep -o '^[A-Z_]*' "$ENV_FILE" | sed 's/^/  /'
echo "Demo logins: $ACCOUNTS_FILE (chmod 600)"
